# Predicting Churn using Customer Behaviour data

Using a Supervised learning technique, person with known condition are correlated with Heart Rate, Sleep Minutes and quality of sleep.
Using gradient boosted Classification model, bulding a model using Heart rate, Sleep minutes and quality of sleep(or REM sleep minutes if availbale).

To Predict Sleep Apnea: 
Pass 

["Heart Rate" , "Average Sleep Minutes" ,"Average WakeMinutes"(or REM sleep minutes if availbale)] to get the Score
0 -> No sleep Apnea
1 -> Has sleep Apena

In [1]:

import sys
import types
import pandas as pd
from botocore.client import Config
import ibm_boto3

def __iter__(self): return 0

# @hidden_cell
# The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# You might want to remove those credentials before you share your notebook.
client_be930c29d85f4c09ad9acaac49542815 = ibm_boto3.client(service_name='s3',
    ibm_api_key_id='e5yrkjNb4k2bfVuXgWYKRKHXIs2V208vfTFotbW9jjdK',
    ibm_auth_endpoint="https://iam.ng.bluemix.net/oidc/token",
    config=Config(signature_version='oauth'),
    endpoint_url='https://s3-api.us-geo.objectstorage.service.networklayer.com')

body = client_be930c29d85f4c09ad9acaac49542815.get_object(Bucket='sleepapnea-donotdelete-pr-3gt261v6npjm1a',Key='DiseasesPredictiondata20180807.csv')['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

df_data_1 = pd.read_csv(body)
df_data_1.head()

,Unnamed: 0,dateTime,Unnamed: 0.1,Unnamed: 0_x,Unnamed: 0_y,dateOfSleep,day,duration,efficiency,endTime,...,pc_chgn_date,restingHeartRate,startTime,timeInBed,type,userId,wake_count,year,isHugeChange,hasSleepApnea
0,0,2017-04-30 00:21:00,45121,197091,45402,2017-04-30,30,26520000,98,2017-04-30T07:43:30.000,...,NaN,62.0,2017-04-30T00:21:30.000,442,stages,5N9LQK,15,2017,False,False
1,1,2017-04-30 00:22:00,45122,197092,45403,2017-04-30,30,26520000,98,2017-04-30T07:43:30.000,...,0.000000,62.0,2017-04-30T00:21:30.000,442,stages,5N9LQK,15,2017,False,False
2,2,2017-04-30 00:23:00,45123,197093,45404,2017-04-30,30,26520000,98,2017-04-30T07:43:30.000,...,0.015152,62.0,2017-04-30T00:21:30.000,442,stages,5N9LQK,15,2017,False,False
3,3,2017-04-30 00:24:00,45124,197094,45405,2017-04-30,30,26520000,98,2017-04-30T07:43:30.000,...,0.014925,62.0,2017-04-30T00:21:30.000,442,stages,5N9LQK,15,2017,False,False
4,4,2017-04-30 00:25:00,45125,197095,45406,2017-04-30,30,26520000,98,2017-04-30T07:43:30.000,...,0.014706,62.0,2017-04-30T00:21:30.000,442,stages,5N9LQK,15,2017,False,False

In [2]:
df_data_1.columns

Index(['Unnamed: 0', 'dateTime', 'Unnamed: 0.1', 'Unnamed: 0_x',
       'Unnamed: 0_y', 'dateOfSleep', 'day', 'duration', 'efficiency',
       'endTime', 'heartRate', 'hour', 'isMainSleep', 'level', 'logId',
       'minute', 'minutesAfterWakeup', 'minutesAsleep', 'minutesAwake',
       'minutesToFallAsleep', 'month', 'pc_chgn_date', 'restingHeartRate',
       'startTime', 'timeInBed', 'type', 'userId', 'wake_count', 'year',
       'isHugeChange', 'hasSleepApnea'],
      dtype='object')

In [3]:
print("List of features with their corresponding count of null values : ")
print("---------------------------------------------------------------- ")
print(df_data_1.isnull().sum())

List of features with their corresponding count of null values :
----------------------------------------------------------------
Unnamed: 0                0
dateTime                  0
Unnamed: 0.1              0
Unnamed: 0_x              0
Unnamed: 0_y              0
dateOfSleep               0
day                       0
duration                  0
efficiency                0
endTime                   0
heartRate                 0
hour                      0
isMainSleep               0
level                  1268
logId                     0
minute                    0
minutesAfterWakeup        0
minutesAsleep             0
minutesAwake              0
minutesToFallAsleep       0
month                     0
pc_chgn_date           1666
restingHeartRate       5513
startTime                 0
timeInBed                 0
type                      0
userId                    0
wake_count                0
year                      0
isHugeChange              0
hasSleepApnea             0
dtype: int64

In [74]:
df_data_1[df_data_1['Resting Heart Rate'].isnull()]

,Member Name,Date,Resting Heart Rate,duration,efficiency,endTime,minutesAsleep,minutesAwake,timeInBed,deep_minutes,light_minutes,rem_minutes,wake_minutes,restless_minutes,asleep_minutes,hasSleepApnea
125,Helena Buehler,10/27/2017,NaN,23880000,98,2017-10-27T06:45:00.000,389,9,398,,,,,9,389,False
213,Helena Buehler,3/9/2018,NaN,26100000,97,2018-03-09T06:35:30.000,401,34,435,80,257,64,34,,,False
281,Helena Buehler,5/14/2018,NaN,19620000,91,2018-05-14T06:50:30.000,298,29,327,,,,,22,298,False
435,Kihyun (Jun) Kim,10/27/2017,NaN,23880000,98,2017-10-27T06:45:00.000,389,9,398,,,,,9,389,False
523,Kihyun (Jun) Kim,3/9/2018,NaN,26100000,97,2018-03-09T06:35:30.000,401,34,435,80,257,64,34,,,False
591,Kihyun (Jun) Kim,5/14/2018,NaN,19620000,91,2018-05-14T06:50:30.000,298,29,327,,,,,22,298,False
745,Heather Griffin,10/27/2017,NaN,23880000,98,2017-10-27T06:45:00.000,389,9,398,,,,,9,389,False
833,Heather Griffin,3/9/2018,NaN,26100000,97,2018-03-09T06:35:30.000,401,34,435,80,257,64,34,,,False
901,Heather Griffin,5/14/2018,NaN,19620000,91,2018-05-14T06:50:30.000,298,29,327,,,,,22,298,False
1055,Kim Benito,10/27/2017,NaN,23880000,98,2017-10-27T06:45:00.000,389,9,398,,,,,9,389,False
1143,Kim Benito,3/9/2018,NaN,26100000,97,2018-03-09T06:35:30.000,401,34,435,80,257,64,34,,,False
1211,Kim Benito,5/14/2018,NaN,19620000,91,2018-05-14T06:50:30.000,298,29,327,,,,,22,298,False
1365,Michael Enslein,10/27/2017,NaN,23880000,98,2017-10-27T06:45:00.000,389,9,398,,,,,9,389,True
1453,Michael Enslein,3/9/2018,NaN,26100000,97,2018-03-09T06:35:30.000,401,34,435,80,257,64,34,,,True
1521,Michael Enslein,5/14/2018,NaN,19620000,91,2018-05-14T06:50:30.000,298,29,327,,,,,22,298,True
1675,Stephen Frye,10/27/2017,NaN,23880000,98,2017-10-27T06:45:00.000,389,9,398,,,,,9,389,False
1763,Stephen Frye,3/9/2018,NaN,26100000,97,2018-03-09T06:35:30.000,401,34,435,80,257,64,34,,,False
1831,Stephen Frye,5/14/2018,NaN,19620000,91,2018-05-14T06:50:30.000,298,29,327,,,,,22,298,False
1985,"Carl E. Patten, II",10/27/2017,NaN,23880000,98,2017-10-27T06:45:00.000,389,9,398,,,,,9,389,False
2073,"Carl E. Patten, II",3/9/2018,NaN,26100000,97,2018-03-09T06:35:30.000,401,34,435,80,257,64,34,,,False
2141,"Carl E. Patten, II",5/14/2018,NaN,19620000,91,2018-05-14T06:50:30.000,298,29,327,,,,,22,298,False
2295,Corrine Bogovich,10/27/2017,NaN,23880000,98,2017-10-27T06:45:00.000,389,9,398,,,,,9,389,False
2383,Corrine Bogovich,3/9/2018,NaN,26100000,97,2018-03-09T06:35:30.000,401,34,435,80,257,64,34,,,False
2451,Corrine Bogovich,5/14/2018,NaN,19620000,91,2018-05-14T06:50:30.000,298,29,327,,,,,22,298,False
2605,Raj Rajarshi,10/27/2017,NaN,23880000,98,2017-10-27T06:45:00.000,389,9,398,,,,,9,389,False
2693,Raj Rajarshi,3/9/2018,NaN,26100000,97,2018-03-09T06:35:30.000,401,34,435,80,257,64,34,,,False
2761,Raj Rajarshi,5/14/2018,NaN,19620000,91,2018-05-14T06:50:30.000,298,29,327,,,,,22,298,False

# Drop the NaN

In [4]:
df_data_1 = df_data_1.dropna(how='any',axis=0)

# Total Data Set

In [5]:
len(df_data_1)

586957

In [6]:
df_data_1['hasSleepApnea'].value_counts()

False    420990
True     165967
Name: hasSleepApnea, dtype: int64

In [7]:
df_data_1['hasSleepApnea'] = df_data_1['hasSleepApnea'].apply(lambda x:0 if x == False else 1)

In [9]:
df_data_1['userId'].drop_duplicates()

1         5N9LQK
111737    28LB8N
135336    2QHZG9
236868    3GSDMJ
405328    3HLR37
411260    3PJ6M2
416034    5VFR42
433751    6P9JQP
444143    57NTMC
474418    5YB5FZ
Name: userId, dtype: object

In [11]:
feature_cols = ['restingHeartRate','minutesAsleep', 'minutesAwake']
features_df = df_data_1[feature_cols]

In [12]:
from sklearn import ensemble
from sklearn import model_selection

# From the Dataset , split the dataset into Testing and training

In [13]:
fitbit_train, fitbit_test, target_train, target_test = model_selection.train_test_split(features_df, df_data_1.loc[:,'hasSleepApnea'], test_size=0.33, random_state=10)

# Train the Model and Get the accuracy

In [14]:
clf1 = ensemble.GradientBoostingClassifier()
clf1.fit(fitbit_train, target_train)
clf1.score(fitbit_test,target_test)

0.8652527672228647

# Use the model to Classify if the person is having Sleep Apnea or Not

In [15]:
testPd = fitbit_test.head(1)

In [16]:
clf1.predict(testPd)

array([0])

If 0 -> No sleep Apneas and 1 -> Has Sleep Apnea